version: '3.0'
services:
  backend:
    build: ./backend
    container_name: backend_c
    ports:
      - '4000:4000'
  frontend:
    build: ./frontend
    container_name: frontend_c
    ports: 
      - '3000:3000'